DATA: Add Post Impression Model & Migration
hassanhabib/Taarafo.Core pull request #201
Opened 2022-03-29 03:58 UTC by ysnarafat

2022-04-09 01:56 UTC, ShriHumrudha requested changes
Are we missing the Reference.cs file?

2022-04-09 02:51 UTC, ysnarafat commented
> Are we missing the Reference.cs file?

I assumed it has to be added later likewise some other PR

2022-04-09 03:00 UTC, ShriHumrudha commented
@ysnarafat Take these references:

https://github.com/hassanhabib/Taarafo.Core/pull/38
https://www.youtube.com/watch?v=XoDwJ-dvhI0

2022-04-13 03:45 UTC, ShriHumrudha approved these changes

2022-04-13 03:51 UTC, merged

2022-04-13 05:35 UTC, ysnarafat commented on Taarafo.Core/Migrations/20220411061952_AddPostImpressionModel.cs
> +        {
Okay