DATA: Implement Model & Migrations for GroupPost
hassanhabib/Taarafo.Core pull request #207
Opened 2022-04-01 02:49 UTC by rcruzfreelance

Close #168

2022-04-09 01:57 UTC, ShriHumrudha requested changes

2022-04-09 01:57 UTC, ShriHumrudha commented on Taarafo.Core/Migrations/20220401024818_AddGroupPostModel.cs
> +﻿using System;
Add copyrights header

2022-04-09 01:57 UTC, ShriHumrudha commented on Taarafo.Core/Models/Groups/Group.cs
> +
Remove extra line

2022-04-09 21:42 UTC, rcruzfreelance commented on Taarafo.Core/Migrations/20220401024818_AddGroupPostModel.cs
> +﻿using System;
done

2022-04-09 21:43 UTC, rcruzfreelance commented on Taarafo.Core/Models/Groups/Group.cs
> +
done

2022-04-11 21:35 UTC, ShriHumrudha approved these changes

2022-04-12 02:15 UTC, rcruzfreelance commented
Can anybody merge these changes they been already approved by @ShriHumrudha

2022-04-13 04:14 UTC, ShriHumrudha commented
@rcruzfreelance Please address the conflicts

2022-04-15 01:57 UTC, rcruzfreelance commented
done

2022-04-16 20:58 UTC, ShriHumrudha approved these changes

2022-04-16 20:58 UTC, merged