FOUNDATIONS: Update Group
hassanhabib/Taarafo.Core pull request #214
Opened 2022-05-09 14:16 UTC by eriadhami

#204

2022-05-14 22:02 UTC, hassanhabib commented
@eriadhami we should change this to `Modify` instead of `Update`.
@ShriHumrudha please take a look at this PR.

2022-05-15 09:18 UTC, eriadhami commented
@hassanhabib I was thinking that for social networks Update was more accurate for business language that's why I didn't use Modify.

2022-05-30 00:32 UTC, hassanhabib commented
@eriadhami please resolve conflicts here.

2022-05-30 05:35 UTC, ShriHumrudha requested changes
I see both Update and Add PRs here.

2022-05-30 05:35 UTC, ShriHumrudha commented on .vscode/launch.json
> +{
Local files should not be checked-in

2022-05-30 05:35 UTC, ShriHumrudha commented on Taarafo.Core.Tests.Unit/Services/Foundations/Groups/GroupServiceTests.Exceptions.Modify.cs
> +            Group someGroup =
Consider moving all the lines till 81 to a single line code back to back. I do not see much troubling pattern if they are on the same line.

2022-07-04 02:12 UTC, closed without merging