BROKERS: Select Event By Id
hassanhabib/Taarafo.Core pull request #293
Opened 2022-09-15 16:11 UTC by Hassaero110

2022-09-15 16:11 UTC, Hassaero110 commented
Closes #256

2022-09-16 21:14 UTC, cjdutoit commented on Taarafo.Core/Brokers/Storages/StorageBroker.Events.cs
> +        public async ValueTask<Event> SelectEventByIdAsync(Guid eventID)
Change to eventId pls

2022-09-16 21:14 UTC, cjdutoit commented on Taarafo.Core/Brokers/Storages/StorageBroker.Events.cs
> +            return await broker.Events.FindAsync(eventID);
Chnage to eventId

2022-09-16 21:15 UTC, cjdutoit requested changes
Please change the two items

2022-09-20 10:41 UTC, cjdutoit approved these changes

2022-09-20 10:42 UTC, merged