DATA: Add PostReport Model
hassanhabib/Taarafo.Core pull request #307
Opened 2022-11-15 08:16 UTC by khusnii

2022-11-15 19:09 UTC, cjdutoit commented
@khusnii always link the issue that you have worked on with the pull request.

i.e. in the description add `closes #199`

Please update both your pull requests.  Thanks

2022-11-15 19:58 UTC, ElbekDeveloper requested changes

2022-11-15 19:58 UTC, ElbekDeveloper commented on Taarafo.Core/Migrations/20221115081202_AddPostReportModel.cs
> +﻿using System;
Header file is missing

2022-11-20 05:29 UTC, ElbekDeveloper approved these changes

2022-11-24 09:58 UTC, merged