DATA: Add GroupMembership Model
hassanhabib/Taarafo.Core pull request #309
Opened 2022-11-17 08:13 UTC by khusnii

closes #164

2022-11-17 08:16 UTC, khusnii reviewed
CODE RUB: Add Header File

2022-11-18 17:53 UTC, ElbekDeveloper requested changes

2022-11-18 17:53 UTC, ElbekDeveloper commented on Taarafo.Core/Migrations/20221117080833_AddGroupMembershipModel.cs
> +    }
When you declare `DbSet<>` in broker files, this migration file will have some code in it. Please, fix this.

2022-11-20 05:27 UTC, ElbekDeveloper requested changes

2022-11-20 05:27 UTC, ElbekDeveloper commented on Taarafo.Core/Migrations/20221119085635_AddGroupMembershipModel.cs
> +﻿using System;
Header

2022-11-25 22:44 UTC, cjdutoit approved these changes

2022-11-27 16:36 UTC, ElbekDeveloper approved these changes

2022-11-27 16:36 UTC, merged