BROKERS: Update Event
hassanhabib/Taarafo.Core pull request #311
Opened 2022-11-18 02:35 UTC by khusnii

closes #257

2022-11-18 17:50 UTC, ElbekDeveloper requested changes

2022-11-18 17:50 UTC, ElbekDeveloper commented on Taarafo.Core/Brokers/Storages/StorageBroker.Events.cs
> +		}
Upgrade this to new Standard

2022-11-19 08:35 UTC, ElbekDeveloper commented
@khusnii conflict

2022-11-19 10:26 UTC, khusnii commented
I'm sorry. I confused between branches. I'll solve

2022-11-20 05:25 UTC, closed without merging