CODE RUB: Upgrade InsertPostAsync()
hassanhabib/Taarafo.Core pull request #318
Opened 2022-11-18 10:20 UTC by khusnii

closes #317

2022-11-18 17:50 UTC, ElbekDeveloper requested changes

2022-11-18 17:50 UTC, ElbekDeveloper commented on Taarafo.Core/Brokers/Storages/StorageBroker.cs
> +
Remove this empty line

2022-11-18 18:36 UTC, khusnii commented on Taarafo.Core/Brokers/Storages/StorageBroker.cs
> +
I removed

2022-11-19 08:10 UTC, ElbekDeveloper approved these changes

2022-11-19 08:15 UTC, ElbekDeveloper commented
@khusnii conflict

2022-11-20 05:03 UTC, ElbekDeveloper approved these changes

2022-11-20 05:03 UTC, merged