FOUNDATIONS: Add Event
hassanhabib/Taarafo.Core pull request #343
Opened 2022-12-08 14:33 UTC by khusnii

closes #259

2022-12-10 09:44 UTC, Javlonbek-dev commented on Taarafo.Core.Tests.Unit/Services/Foundations/Events/EventServiceTests.Logic.Add.cs
> +                .ReturnsAsync(storageEvent);
Tab

2022-12-10 10:57 UTC, Javlonbek-dev commented on Taarafo.Core.Tests.Unit/Services/Foundations/Events/EventServiceTests.Logic.Add.cs
> +                .ReturnsAsync(storageEvent);
Tab here

2022-12-10 10:57 UTC, cjdutoit requested changes
Hi @khusnii, you need to add the validation and exception tests for Add.

2022-12-10 10:58 UTC, Javlonbek-dev commented on Taarafo.Core.Tests.Unit/Services/Foundations/Events/EventServiceTests.Logic.Add.cs
> +                .ReturnsAsync(storageEvent);
Tab here

2022-12-30 12:54 UTC, cjdutoit commented on Taarafo.Core.Tests.Unit/Services/Foundations/Events/EventServiceTests.Exceptions.Add.cs
> +    }
Can you also add these tests:
`public async Task ShouldThrowDependencyValidationExceptionOnAddIfEventAlreadyExsitsAndLogItAsync()`

`public async Task ShouldThrowDependencyExceptionOnAddIfDatabaseUpdateErrorOccursAndLogItAsync()`

`public async Task ShouldThrowServiceExceptionOnAddIfServiceErrorOccursAndLogItAsync()`

2023-02-04 22:52 UTC, cjdutoit commented
@khusnii  going to close this PR as it's inactive.

2023-02-04 22:52 UTC, closed without merging