CODE RUB: Remove OpenAPI hard coding
hassanhabib/Taarafo.Core pull request #37
Opened 2021-10-24 13:44 UTC by BrianLParker

This PR moves all the OpenAPI (Swagger) document configuration to `appsettings.Development.json`. 

![swagger](https://user-images.githubusercontent.com/8317299/138596881-667d3524-75e0-4ab4-aedc-cca8b3355a92.png)

2021-10-25 00:44 UTC, ShriHumrudha requested changes

2021-10-25 00:44 UTC, ShriHumrudha commented on Taarafo.Core/Startup.cs
> +
Line 34 can be removed

2021-10-25 00:44 UTC, ShriHumrudha commented on Taarafo.Core/Startup.cs
> +            services.AddScoped<LocalConfigurations>(sp => localConfigurations);
what is sp here? Can we have a more readable name?

2021-10-25 00:44 UTC, ShriHumrudha commented on Taarafo.Core/Startup.cs
> +                            url: openAPIConfiguration.OpenAPIEndpoint.Url,
We can remove the parameter aliasing as the ending property name is same as the parameter name.

2021-10-25 00:44 UTC, ShriHumrudha commented on Taarafo.Core/Startup.cs
> +                services.AddSwaggerGen(options =>
Need a line break here and inside the OpenApiInfo model too.

2021-10-25 00:44 UTC, ShriHumrudha commented on Taarafo.Core/Startup.cs
> +                    OpenApiInfo openApiInfo = new OpenApiInfo
left hand side can be var as the right hand side is clear.

2021-10-25 00:44 UTC, ShriHumrudha commented on Taarafo.Core/Startup.cs
> +
This line can be removed.

2021-10-29 19:12 UTC, hassanhabib commented
Closing due to no activity

2021-10-29 19:12 UTC, closed without merging