FOUNDATIONS: Modify Group Posts
hassanhabib/Taarafo.Core pull request #412
Opened 2023-01-04 13:28 UTC by jasurbekyusuf

Closes #390

2023-01-04 20:02 UTC, GulchexrasGithub approved these changes

2023-01-05 15:34 UTC, cjdutoit commented on Taarafo.Core/Models/GroupPosts/GroupPost.cs
> +        public DateTimeOffset CreatedDate { get; set; }
Remove this line, we don't need this here

2023-01-05 15:35 UTC, cjdutoit commented on Taarafo.Core/Models/GroupPosts/GroupPost.cs
> +        public DateTimeOffset UpdatedDate { get; set; }
Remove this line, we don't need this here

2023-01-05 15:36 UTC, cjdutoit commented on Taarafo.Core/Services/Foundations/GroupPosts/GroupPostService.cs
> +        public ValueTask<GroupPost> ModifyGroupPostAsync(GroupPost groupPost) =>
Remove the DateTimeBroker as we do not need this dependency

2023-01-05 15:36 UTC, cjdutoit commented on Taarafo.Core.Tests.Unit/Services/Foundations/GroupPosts/GroupPostServiceTests.cs
> +        public static TheoryData MinutesBeforeOrAfter()
Remove the DateTimeBroker as we do not need this dependency

2023-01-05 15:38 UTC, cjdutoit commented on Taarafo.Core.Tests.Unit/Services/Foundations/GroupPosts/GroupPostServiceTests.Validations.Modify.cs
> +
Remove extra line

2023-01-05 15:38 UTC, cjdutoit commented on Taarafo.Core.Tests.Unit/Services/Foundations/GroupPosts/GroupPostServiceTests.Validations.Modify.cs
> +            this.dateTimeBrokerMock.Setup(broker =>
Remove this

2023-01-05 15:39 UTC, cjdutoit commented on Taarafo.Core.Tests.Unit/Services/Foundations/GroupPosts/GroupPostServiceTests.Validations.Modify.cs
> +            this.dateTimeBrokerMock.Verify(broker =>
Remove this

2023-01-05 15:39 UTC, cjdutoit commented on Taarafo.Core.Tests.Unit/Services/Foundations/GroupPosts/GroupPostServiceTests.Validations.Modify.cs
> +            this.dateTimeBrokerMock.VerifyNoOtherCalls();
remove this

2023-01-05 15:41 UTC, cjdutoit commented on Taarafo.Core.Tests.Unit/Services/Foundations/GroupPosts/GroupPostServiceTests.Validations.Modify.cs
> +            DateTimeOffset randomDateTime = GetRandomDateTimeOffset();
Remove this

2023-01-05 15:42 UTC, cjdutoit commented on Taarafo.Core.Tests.Unit/Services/Foundations/GroupPosts/GroupPostServiceTests.Validations.Modify.cs
> +            GroupPost randomGroupPost = CreateRandomGroupPost(randomDateTime);
change to `GroupPost randomGroupPost = CreateRandomGroupPost();`

2023-01-05 15:43 UTC, cjdutoit commented on Taarafo.Core.Tests.Unit/Services/Foundations/GroupPosts/GroupPostServiceTests.Validations.Modify.cs
> +        public async Task ShouldThrowValidationExceptionOnModifyIfUpdatedDateIsSameAsCreatedDateAndLogItAsync()
Can remove this test as we do not have any dates on GroupPost

2023-01-05 15:47 UTC, cjdutoit commented on Taarafo.Core.Tests.Unit/Services/Foundations/GroupPosts/GroupPostServiceTests.Validations.Modify.cs
> +        public async Task ShouldThrowValidationExceptionOnModifyIfUpdatedDateIsNotRecentAndLogItAsync(int minutes)
Can remove this test as we do not have any dates on GroupPost

2023-01-05 15:47 UTC, cjdutoit commented on Taarafo.Core.Tests.Unit/Services/Foundations/GroupPosts/GroupPostServiceTests.Validations.Modify.cs
> +            DateTimeOffset dateTime = GetRandomDateTimeOffset();
Update this as above...remove the DateTime

2023-01-05 15:48 UTC, cjdutoit commented on Taarafo.Core.Tests.Unit/Services/Foundations/GroupPosts/GroupPostServiceTests.Validations.Modify.cs
> +            this.dateTimeBrokerMock.Verify(broker =>
Remove this

2023-01-05 15:48 UTC, cjdutoit commented on Taarafo.Core.Tests.Unit/Services/Foundations/GroupPosts/GroupPostServiceTests.Validations.Modify.cs
> +            this.dateTimeBrokerMock.VerifyNoOtherCalls();
remove this

2023-01-05 15:49 UTC, cjdutoit commented on Taarafo.Core.Tests.Unit/Services/Foundations/GroupPosts/GroupPostServiceTests.Validations.Modify.cs
> +            GroupPost randomGroupPost = CreateRandomModifyGroupPost(randomDateTime);
Update as above

2023-01-05 15:49 UTC, cjdutoit commented on Taarafo.Core.Tests.Unit/Services/Foundations/GroupPosts/GroupPostServiceTests.Validations.Modify.cs
> +            this.dateTimeBrokerMock.Setup(broker =>
Remove this

2023-01-05 15:49 UTC, cjdutoit commented on Taarafo.Core.Tests.Unit/Services/Foundations/GroupPosts/GroupPostServiceTests.Validations.Modify.cs
> +            this.dateTimeBrokerMock.Verify(broker =>
Remove this

2023-01-05 15:57 UTC, cjdutoit commented on Taarafo.Core.Tests.Unit/Services/Foundations/GroupPosts/GroupPostServiceTests.Validations.Modify.cs
> +            this.dateTimeBrokerMock.Setup(broker =>
Remove

2023-01-05 15:58 UTC, cjdutoit commented on Taarafo.Core.Tests.Unit/Services/Foundations/GroupPosts/GroupPostServiceTests.Validations.Modify.cs
> +            this.dateTimeBrokerMock.Verify(broker =>
remove

2023-01-05 16:04 UTC, cjdutoit commented on Taarafo.Core.Tests.Unit/Services/Foundations/GroupPosts/GroupPostServiceTests.Exceptions.Modify.cs
> +            GroupPost randomGroupPost = CreateRandomGroupPost(someDateTime);
Remove the datetime

2023-01-05 16:08 UTC, cjdutoit commented on Taarafo.Core.Tests.Unit/Services/Foundations/GroupPosts/GroupPostServiceTests.Exceptions.Modify.cs
> +                broker.GetCurrentDateTimeOffset(), Times.Once);
change this to:
```
    this.dateTimeBrokerMock.Verify(broker =>
        broker.GetCurrentDateTimeOffset(), Times.Once);
```
also update the other places

2023-01-05 16:08 UTC, cjdutoit requested changes
Some changes required

2023-01-16 15:21 UTC, cjdutoit approved these changes

2023-01-16 15:22 UTC, merged