EXPOSERS: Post Group
hassanhabib/Taarafo.Core pull request #428
Opened 2023-01-09 16:04 UTC by StudentofTATU

Closes #391

2023-01-09 17:59 UTC, GulchexrasGithub commented on Taarafo.Core/Controllers/GroupsController.cs
> +            catch (GroupDependencyException groupDependencyException)
it should be:   `catch (GroupDependencyValidationException groupDependencyValidationException)
                when (groupDependencyValidationException.InnerException is InvalidGroupReferenceException)
            {
                return FailedDependency(groupDependencyValidationException.InnerException);
            }`

2023-01-10 13:59 UTC, GulchexrasGithub approved these changes

2023-01-10 19:38 UTC, cjdutoit requested changes
@StudentofTATU please provide screenshots from either Postman or Swagger to show your exposer is working.

2023-01-11 11:57 UTC, StudentofTATU commented
Created 201:
![image](https://user-images.githubusercontent.com/58965761/211800123-653bbeaf-ba0e-4464-9a18-91abfa1ec746.png)

Bad Request 400:
![image](https://user-images.githubusercontent.com/58965761/211800514-f20a99c0-d2e6-447c-8b14-bee7744abf8c.png)

Conflict 409:
![image](https://user-images.githubusercontent.com/58965761/211800571-68803fdc-a0ac-4b28-8afd-940e8680d3b9.png)

2023-01-12 09:42 UTC, cjdutoit approved these changes

2023-01-12 09:42 UTC, merged