CODE RUB: Removed DateTime Broker from Group Post
hassanhabib/Taarafo.Core pull request #463
Opened 2023-01-26 13:03 UTC by GulchexrasGithub

2023-01-27 18:15 UTC, GulchexrasGithub commented
@cjdutoit Could you have a look, it works on my machine

2023-02-04 23:41 UTC, cjdutoit commented on Taarafo.Core.Tests.Unit/Services/Foundations/GroupPosts/GroupPostServiceTests.Validations.Modify.cs
> -            this.dateTimeBrokerMock.Setup(broker =>
Test also needs to validate for Guid.Empty

2023-02-22 19:44 UTC, cjdutoit commented on Taarafo.Core.Tests.Unit/Services/Foundations/GroupPosts/GroupPostServiceTests.cs
>          private static GroupPost CreateRandomModifyGroupPost(DateTimeOffset dates)
Change this to `private static GroupPost CreateRandomModifyGroupPost()`

2023-02-22 19:45 UTC, cjdutoit commented on Taarafo.Core.Tests.Unit/Services/Foundations/GroupPosts/GroupPostServiceTests.cs
>          private static GroupPost CreateRandomModifyGroupPost(DateTimeOffset dates)
Change this to `private static GroupPost CreateRandomModifyGroupPost()`

2023-02-22 19:51 UTC, cjdutoit requested changes
Some more changes required to remove the dates

2023-03-07 09:25 UTC, GulchexrasGithub commented
> In `Taarafo.Core.Tests.Unit/Services/Foundations/GroupPosts/GroupPostServiceTests.Validations.Modify.cs` Since this is only one invalid value, it is better to make this test `[Fact]` and assign invalid value inside the test.

![image](https://user-images.githubusercontent.com/85836099/223379302-60c286da-b693-4a00-9e16-783e68ca210f.png)
but, have 2 invalid values not one.

2023-08-14 22:15 UTC, closed without merging